name: Harness Android

on:
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - 'src/**'
      - 'example/**'
      - 'package.json'
      - '.github/workflows/harness-android.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'android/**'
      - 'src/**'
      - 'example/**'
      - 'package.json'
      - '.github/workflows/harness-android.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  harness-android:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Build Android APK (debug)
        env:
          JAVA_OPTS: "-XX:MaxHeapSize=6g"
        run: |
          cd example/android
          ./gradlew assembleDebug --no-daemon -PreactNativeArchitectures=x86_64

      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false
          android: false

      - name: Run harness tests
        uses: callstackincubator/react-native-harness@v1
        with:
          app: android/app/build/outputs/apk/debug/app-debug.apk
          runner: android
          projectRoot: example
